#!/bin/bash
#
# Keep track of unattended reboots (crashs)
#
# Copyright © 2014-2025 Mathias Bocquet (mbocquet@sekoya.org)

name="$(basename "${0}")"
date="$(date '+%F %H:%M:%S')"

do_start() {
    # check if control file generated at shutdown is there
    # shellcheck disable=SC2154
    if [ -f "${controlfile}" ]
    then    # boot was attended !
        message="boot"
        ntfy_priority="${ntfy_normal_priority}"
        ntfy_tags="${ntfy_normal_tags}"
        # remove control file
        rm "${controlfile}"
    else    # boot was unattended !
        message="crash boot"
        ntfy_priority="${ntfy_crash_priority}"
        ntfy_tags="${ntfy_crash_tags}"
    fi
    # shellcheck disable=SC2154
    printf "[%s] %s\n" "${date}" "${message}" >> "${logfile}"
    # send alert(s)
    # shellcheck disable=SC2154
    if [[ "${notifications}" =~ "email" ]]
    then
        printf "[%s] %s@%s %s" "${date}" "${name}" "${HOSTNAME}" "${message}"|mail -s "${name}@${HOSTNAME} ${message}" "${email}"
    fi
    # shellcheck disable=SC2154
    if [[ "${notifications}" =~ "ntfy" ]]
    then
    curl \
        -d "${message}" \
        -H "Title: ${HOSTNAME}" \
        -H "Priority: ${ntfy_priority}" \
        -H "Tags: ${ntfy_tags}" \
        -u :"${ntfy_token}" \
        "${ntfy_url}"
    fi
}

do_stop() {
    # write the control file
    touch "${controlfile}"
    printf "[%s] shutdown\n" "${date}" >> "${logfile}"
    return 0
}

case "${1}" in
    start)
        do_start
        ;;
    stop)
        do_stop
        ;;
    *)
        printf "Usage: %s {start|stop}\n" "${name}" >&2
        exit 1
        ;;
esac
